[novel]
encrypt_key = '$+(hT5-?#k8D^*N3'
is_new_days_delta = 15
allowed_extensions = ["png", "jpg", "jpeg", "gif"]
providers = '''
    {
        "qingyuedu": "轻阅读",
        "wzzww": "万众中文",
        "zjyd": "指尖阅读",
        "jiuku": "九库",
        "motie": "魔铁",
        "tadu": "塔读",
        "kanshu": "看书",
        "qichuang": "起创",
        "huoxing": "火星",
        "yueming": "阅明",
        "hxtk": "华夏",
        "yueyou": "阅友",
        "zhulang": "逐浪",
        "heiyan": "黑岩"
    }
'''
categories = '''
    {
      "101": {
        "name": "古代言情",
        "gender": 1,
        "children": {
          "101001": "穿越时空",
          "101002": "宫围争斗",
          "101003": "女强女尊",
          "101004": "种田经商",
          "101005": "世家宅斗",
          "101006": "架空历史"
        }
      },
      "102": {
        "name": "现代言情",
        "gender": 1,
        "children": {
          "102001": "豪门总裁",
          "102002": "现代重生",
          "102003": "婚恋情感",
          "102004": "军婚高干",
          "102005": "穿越时空",
          "102006": "民国情仇"
        }
      },
      "103": {
        "name": "玄幻言情",
        "gender": 1,
        "children": {
          "103001": "幻想",
          "103002": "江湖奇缘"
        }
      },
      "104": {
        "name": "浪漫青春",
        "gender": 1,
        "children": {
          "104001": "青春校园",
          "104002": "禁忌绝恋",
          "104003": "疼痛文学",
          "104004": "成长励志",
          "104005": "校园异能",
          "104006": "唯美纯爱",
          "104007": "网配快穿"
        }
      },
      "105": {
        "name": "仙侠奇缘",
        "gender": 1,
        "children": {
          "105001": "仙侣情缘",
          "105002": "妖精幻情",
          "105003": "古典仙侠",
          "105004": "魔法异能",
          "105005": "重生爱恋",
          "105006": "穿越时空",
          "105007": "奇幻修真",
          "105008": "武侠情缘"
        }
      },
      "106": {
        "name": "耽美百合",
        "gender": 1,
        "children": {
          "106001": "耽美小说",
          "106002": "百合之恋"
        }
      },
      "107": {
        "name": "同人衍生",
        "gender": 1,
        "children": {
          "107001": "动漫同人",
          "107002": "小说同人",
          "107003": "明星同人"
        }
      },
      "108": {
        "name": "N次元",
        "gender": 1,
        "children": {
          "108001": "唯美幻想",
          "108002": "动漫同人",
          "108003": "小说同人",
          "108004": "明星同人",
          "108005": "青春日常",
          "108006": "萌系变身",
          "108007": "灵异同人"
        }
      },
      "109": {
        "name": "游戏情缘",
        "gender": 1,
        "children": {
          "109001": "网络情缘",
          "109002": "电子竞技"
        }
      },
      "110": {
        "name": "科幻情缘",
        "gender": 1,
        "children": {
          "110001": "末世危机",
          "110002": "星际科幻"
        }
      },
      "201": {
        "name": "玄幻",
        "gender": 2,
        "children": {
          "201001": "东方玄幻",
          "201002": "异世大陆"
        }
      },
      "202": {
        "name": "修真武侠",
        "gender": 2,
        "children": {
          "202001": "新派武侠",
          "202002": "经典武侠",
          "202003": "国术古武",
          "202004": "现代修真"
        }
      },
      "203": {
        "name": "仙侠",
        "gender": 2,
        "children": {
          "203001": "古典仙侠",
          "203002": "奇幻修真",
          "203003": "洪荒传说"
        }
      },
      "204": {
        "name": "都市异能",
        "gender": 2,
        "children": {
          "204001": "都市生活",
          "204002": "异术超能",
          "204003": "都市修仙",
          "204004": "屌丝逆袭",
          "204005": "种田文"
        }
      },
      "205": {
        "name": "奇幻",
        "gender": 2,
        "children": {
          "205001": "西方奇幻",
          "205002": "异类兽族",
          "205003": "魔法校园"
        }
      },
      "206": {
        "name": "科幻",
        "gender": 2,
        "children": {
          "206001": "未来世界",
          "206002": "末世进化",
          "206003": "时空穿梭"
        }
      },
      "207": {
        "name": "二次元",
        "gender": 2,
        "children": {
          "207001": "搞笑吐槽",
          "207002": "原生幻想",
          "207003": "衍生同人"
        }
      },
      "208": {
        "name": "历史",
        "gender": 2,
        "children": {
          "208001": "架空历史",
          "208002": "历史传记"
        }
      },
      "209": {
        "name": "游戏",
        "gender": 2,
        "children": {
          "209001": "虚拟网游",
          "209002": "游戏异界",
          "209003": "电子竞技"
        }
      },
      "210": {
        "name": "军事",
        "gender": 2,
        "children": {
          "210001": "现代军事",
          "210002": "战争幻想",
          "210003": "抗日烽火"
        }
      },
      "211": {
        "name": "现实",
        "gender": 2,
        "children": {
          "211001": "青春文学",
          "211002": "现实百态"
        }
      },
      "001": {
        "name": "短篇",
        "gender": 0,
        "children": {
          "001001": "女生短篇",
          "001002": "男生短篇"
        }
      },
      "002": {
        "name": "灵异惊悚",
        "gender": 0,
        "children": {
          "002001": "幽冥情缘",
          "002002": "神秘文化",
          "002003": "悬疑探险",
          "002004": "恐怖惊悚",
          "002005": "灵异鬼怪",
          "002006": "风水密术"
        }
      },
      "003": {
        "name": "悬疑推理",
        "gender": 0,
        "children": {
          "003001": "寻墓探险",
          "003002": "侦探推理",
          "003003": "爱情推理",
          "003004": "推理搞怪"
        }
      }
    }
'''

[novel-memo] # 备忘，未使用
categories_us = '''
    {
      "103": {
        "name": "Fanfiction",
        "gender": 1,
        "children": {
          "103001": "Fanfiction"
        }
      },
      "104": {
        "name": "LGBT",
        "gender": 1,
        "children": {
          "104001": "LGBT"
        }
      },
      "105": {
        "name": "Sci-fi",
        "gender": 1,
        "children": {
          "105001": "Sci-fi"
        }
      },
      "106": {
        "name": "Modern",
        "gender": 1,
        "children": {
          "106001": "Modern"
        }
      },
      "107": {
        "name": "Romance",
        "gender": 1,
        "children": {
          "107001": "Romance"
        }
      },
      "201": {
        "name": "Wuxia",
        "gender": 2,
        "children": {
          "201001": "Wuxia"
        }
      },
      "202": {
        "name": "Fantasy",
        "gender": 2,
        "children": {
          "202001": "Fantasy"
        }
      },
      "203": {
        "name": "History",
        "gender": 2,
        "children": {
          "203001": "History"
        }
      },
      "204": {
        "name": "Military",
        "gender": 2,
        "children": {
          "204001": "Military"
        }
      },
      "205": {
        "name": "Realistic",
        "gender": 1,
        "children": {
          "205001": "Realistic"
        }
      },
      "001": {
        "name": "Short Stories",
        "gender": 0,
        "children": {
          "001001": "female short",
          "001002": "male short"
        }
      },
      "002": {
        "name": "Horror&Thriller",
        "gender": 0,
        "children": {
          "002001": "Horror&Thriller"
        }
      },
      "003": {
        "name": "Mystery",
        "gender": 0,
        "children": {
          "003001": "Mystery"
        }
      },
      "004": {
        "name": "ACG",
        "gender": 0,
        "children": {
          "004001": "ACG"
        }
      },
      "005": {
        "name": "Vampire&Werewolf",
        "gender": 0,
        "children": {
          "005001": "Vampire&Werewolf"
        }
      }
    }
'''

categories_msg = '''
    {
      "103": {
        "name": "Fanfiction",
        "gender": 1,
        "children": {
          "103001": "Fanfiction"
        }
      },
      "104": {
        "name": "LGBT",
        "gender": 1,
        "children": {
          "104001": "LGBT"
        }
      },
      "105": {
        "name": "Sci-fi",
        "gender": 1,
        "children": {
          "105001": "Sci-fi"
        }
      },
      "106": {
        "name": "Modern",
        "gender": 1,
        "children": {
          "106001": "Modern"
        }
      },
      "107": {
        "name": "Romance",
        "gender": 1,
        "children": {
          "107001": "Romance"
        }
      },
      "201": {
        "name": "Wuxia",
        "gender": 2,
        "children": {
          "201001": "Wuxia"
        }
      },
      "202": {
        "name": "Fantasy",
        "gender": 2,
        "children": {
          "202001": "Fantasy"
        }
      },
      "203": {
        "name": "History",
        "gender": 2,
        "children": {
          "203001": "History"
        }
      },
      "204": {
        "name": "Military",
        "gender": 2,
        "children": {
          "204001": "Military"
        }
      },
      "205": {
        "name": "Realistic",
        "gender": 1,
        "children": {
          "205001": "Realistic"
        }
      },
      "001": {
        "name": "Short Stories",
        "gender": 0,
        "children": {
          "001001": "female short",
          "001002": "male short"
        }
      },
      "002": {
        "name": "Horror&Thriller",
        "gender": 0,
        "children": {
          "002001": "Horror&Thriller"
        }
      },
      "003": {
        "name": "Mystery",
        "gender": 0,
        "children": {
          "003001": "Mystery"
        }
      },
      "004": {
        "name": "ACG",
        "gender": 0,
        "children": {
          "004001": "ACG"
        }
      },
      "005": {
        "name": "Vampire&Werewolf",
        "gender": 0,
        "children": {
          "005001": "Vampire&Werewolf"
        }
      }
    }
'''
