[default]
log_level = 'info'
log_format = '%(asctime)s [%(levelname)s] %(filename)s@%(lineno)s - %(funcName)s(): %(message)s'
log_size = 52428800
products = ['geezios']


[flask]
host = '127.0.0.1'
port = 8800
debug = false

[mongodb]
url = 'mongodb://172.19.68.182:27017'
database = 'whale'
auth = true
user = 'whale'
pass = 'Whale123$%^'
replica_set = ''
